In [1]:
import numpy as np

In [2]:
A = np.array([[0, 1],
              [2, 3],
              [4, 5]])

B = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7]])

In [3]:
multiply = np.dot(A, B)

In [4]:
print(multiply)

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


In [5]:
print(multiply.max())

47
